services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.3'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.3/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
            - keydb
    pgsql:
        image: 'postgres:16'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './vendor/laravel/sail/database/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - '${DB_DATABASE}'
                - '-U'
                - '${DB_USERNAME}'
            retries: 3
            timeout: 5s
    pgadmin:
        image: 'dpage/pgadmin4:latest'
        ports:
            - '${PGADMIN_PORT:-5050}:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: '${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}'
            PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-secret}'
        volumes:
            - 'sail-pgadmin:/var/lib/pgadmin'
        networks:
            - sail
        depends_on:
            - pgsql
    keydb:
        image: 'eqalpha/keydb:latest'
        ports:
            - '${FORWARD_KEYDB_PORT:-6379}:6379'
        volumes:
            - 'sail-keydb:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "keydb-cli", "ping"]
            retries: 3
            timeout: 5s

    redis-commander:
        image: 'rediscommander/redis-commander:latest'
        ports:
            - '${REDIS_COMMANDER_PORT:-8081}:8081'
        environment:
            REDIS_HOSTS: 'local:keydb:6379'
        networks:
            - sail
        depends_on:
            - keydb
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
    sail-keydb:
        driver: local
    sail-pgadmin:
        driver: local
